package pe.greenminds.ecomind.monetization.interfaces.acl;
import java.time.*; import java.util.*; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional; import pe.greenminds.ecomind.monetization.application.commandservices.GemWalletCommandService; import pe.greenminds.ecomind.monetization.application.internal.commandservices.InventoryCommandService; import pe.greenminds.ecomind.monetization.application.outboundservices.MonetizationEventPublisher; import pe.greenminds.ecomind.monetization.domain.model.valueobjects.*; import pe.greenminds.ecomind.monetization.infrastructure.persistence.jpa.entities.ProcessedMonetizationRequestPersistenceEntity; import pe.greenminds.ecomind.monetization.infrastructure.persistence.jpa.repositories.*; import pe.greenminds.ecomind.monetization.interfaces.acl.events.*;
@Component public class MonetizationContextFacadeImpl implements MonetizationContextFacade{
 private final GemWalletCommandService wallet;private final InventoryCommandService inventory;private final UserMultiplierPersistenceRepository multipliers;private final MonetizationEventPublisher events;private final ProcessedMonetizationRequestPersistenceRepository processed;
 public MonetizationContextFacadeImpl(GemWalletCommandService w,InventoryCommandService i,UserMultiplierPersistenceRepository m,MonetizationEventPublisher e,ProcessedMonetizationRequestPersistenceRepository p){wallet=w;inventory=i;multipliers=m;events=e;processed=p;}
 public Optional<ActiveXpMultiplier> getActiveMultiplier(Long user,Instant at){return multipliers.findActive(user,at).stream().findFirst().map(x->new ActiveXpMultiplier(UUID.fromString(x.getId()),x.getFactor(),x.getStartsAt(),x.getExpiresAt()));}
 public void creditRewardGems(CreditRewardGems c){wallet.credit(c.userId(),c.gems(),GemMovementType.REWARD_CREDIT,GemMovementOrigin.QUEST,c.rewardId());}
 @Transactional public void grantCosmeticReward(GrantCosmeticReward c){if(processed.existsById(c.awardId().toString()))return;inventory.grantCosmetic(c.userId(),c.cosmeticId());mark(c.awardId(),"COSMETIC_REWARD");}
 @Transactional public void requestStreakProtection(ConsumeStreakProtector c){if(processed.existsById(c.requestId().toString()))return;var now=Instant.now();if(inventory.consumeProtector(c.userId()))events.publish(new StreakProtectedIntegrationEvent(UUID.randomUUID(),c.requestId(),c.userId(),c.streakDate(),now));else events.publish(new StreakProtectionUnavailableIntegrationEvent(UUID.randomUUID(),c.requestId(),c.userId(),c.streakDate(),now));mark(c.requestId(),"STREAK_PROTECTION");}
 private void mark(UUID id,String operation){var e=new ProcessedMonetizationRequestPersistenceEntity();e.setRequestId(id.toString());e.setOperation(operation);e.setProcessedAt(Instant.now());processed.save(e);}
}
