spring.application.name=ecomind-backend
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=pe.greenminds.ecomind.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
