package pe.greenminds.ecomind.community.interfaces.rest;

import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.validation.Valid;import java.util.List;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import pe.greenminds.ecomind.community.application.commandservices.PostCommandService;import pe.greenminds.ecomind.community.application.queryservices.PostQueryService;import pe.greenminds.ecomind.community.application.queryservices.PostReactionQueryService;import pe.greenminds.ecomind.community.domain.model.commands.DeletePostCommand;import pe.greenminds.ecomind.community.domain.model.queries.SearchPostsQuery;import pe.greenminds.ecomind.community.interfaces.rest.resources.*;import pe.greenminds.ecomind.community.interfaces.rest.transform.PostResourceFromEntityAssembler;import pe.greenminds.ecomind.community.interfaces.rest.transform.CreatePostCommandFromResourceAssembler;import pe.greenminds.ecomind.shared.interfaces.rest.transform.ResponseEntityAssembler;
@RestController @Tag(name="Post",description="Community feed posts") @RequestMapping(value="/api/v1/Community/Posts",produces=MediaType.APPLICATION_JSON_VALUE)
public class PostController{private final PostCommandService commands;private final PostQueryService queries;private final PostReactionQueryService reactions;private final ResponseEntityAssembler responses;public PostController(PostCommandService c,PostQueryService q,PostReactionQueryService r,ResponseEntityAssembler a){commands=c;queries=q;reactions=r;responses=a;}
 @GetMapping public List<PostResource> list(@RequestParam(required=false)Long community_id){return queries.handle(new SearchPostsQuery(community_id)).stream().map(p->PostResourceFromEntityAssembler.toResourceFromEntity(p,reactions.countByPostId(p.id()))).toList();}
 @PostMapping(consumes=MediaType.APPLICATION_JSON_VALUE)public ResponseEntity<?> create(@Valid @RequestBody CreatePostResource r){var c=CreatePostCommandFromResourceAssembler.toCommandFromResource(r);return responses.toResponseEntityFromResult(commands.handle(c),post->PostResourceFromEntityAssembler.toResourceFromEntity(post,0),HttpStatus.CREATED);}
 @DeleteMapping("/{id}")public ResponseEntity<?> delete(@PathVariable Long id,@RequestParam Long user_id){return responses.toResponseEntityFromResult(commands.handle(new DeletePostCommand(id,user_id)),v->null,HttpStatus.NO_CONTENT);}
}
