-- Apply after the imported Community schema. Additive; no data is deleted or inferred.
BEGIN;
DO $$
BEGIN
  IF to_regclass('public.community_communities') IS NULL THEN
    RAISE EXCEPTION 'Import Community schema before applying this migration';
  END IF;
  IF EXISTS (SELECT 1 FROM achievement_share_requests WHERE community_id !~ '^[1-9][0-9]*$'
      OR (publication_id IS NOT NULL AND publication_id !~ '^[1-9][0-9]*$'))
     OR EXISTS (SELECT 1 FROM achievement_awards WHERE community_id IS NOT NULL AND community_id !~ '^[1-9][0-9]*$')
     OR EXISTS (SELECT 1 FROM gamification_outbox WHERE community_id IS NOT NULL AND community_id !~ '^[1-9][0-9]*$') THEN
    RAISE EXCEPTION 'Prototype UUID references require an explicit canonical Community/post mapping';
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS community_achievement_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id VARCHAR(36) NOT NULL UNIQUE,
  award_id VARCHAR(36) NOT NULL,
  author_id BIGINT NOT NULL CHECK (author_id > 0),
  community_id BIGINT NOT NULL REFERENCES community_communities(id),
  published_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_community_achievement_posts_period
  ON community_achievement_posts (community_id, published_at DESC, id DESC);
CREATE TABLE IF NOT EXISTS community_achievement_notices (
  award_id VARCHAR(36) PRIMARY KEY,
  achievement_id VARCHAR(36) NOT NULL,
  user_id BIGINT NOT NULL CHECK (user_id > 0),
  occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
COMMIT;
